/********************************************************************
* macroDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error macroDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemacroDict();
extern void G__cpp_setup_inheritancemacroDict();
extern void G__cpp_setup_typetablemacroDict();
extern void G__cpp_setup_memvarmacroDict();
extern void G__cpp_setup_globalmacroDict();
extern void G__cpp_setup_memfuncmacroDict();
extern void G__cpp_setup_funcmacroDict();
extern void G__set_cpp_environmentmacroDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "macro.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__macroDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__macroDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroDictLN_TList;
extern G__linked_taginfo G__macroDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__macroDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroDictLN_TQObjSender;
extern G__linked_taginfo G__macroDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__macroDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__macroDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__macroDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__macroDictLN_TCanvas;
extern G__linked_taginfo G__macroDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__macroDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__macroDictLN_TH1D;
extern G__linked_taginfo G__macroDictLN_TH1;
extern G__linked_taginfo G__macroDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__macroDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__macroDictLN_TH2D;
extern G__linked_taginfo G__macroDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__macroDictLN_TMacro;
extern G__linked_taginfo G__macroDictLN_TGraphErrors;
extern G__linked_taginfo G__macroDictLN_macro;

/* STUB derived class for protected member access */
