//
// File generated by rootcint at Fri Mar 22 15:40:35 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME mom_corrDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "mom_corrDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void mom_corr_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void mom_corr_Dictionary();
   static void *new_mom_corr(void *p = 0);
   static void *newArray_mom_corr(Long_t size, void *p);
   static void delete_mom_corr(void *p);
   static void deleteArray_mom_corr(void *p);
   static void destruct_mom_corr(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::mom_corr*)
   {
      ::mom_corr *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::mom_corr),0);
      static ::ROOT::TGenericClassInfo 
         instance("mom_corr", "./mom_corr.h", 10,
                  typeid(::mom_corr), DefineBehavior(ptr, ptr),
                  0, &mom_corr_Dictionary, isa_proxy, 0,
                  sizeof(::mom_corr) );
      instance.SetNew(&new_mom_corr);
      instance.SetNewArray(&newArray_mom_corr);
      instance.SetDelete(&delete_mom_corr);
      instance.SetDeleteArray(&deleteArray_mom_corr);
      instance.SetDestructor(&destruct_mom_corr);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::mom_corr*)
   {
      return GenerateInitInstanceLocal((::mom_corr*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::mom_corr*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void mom_corr_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::mom_corr*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_mom_corr(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::mom_corr : new ::mom_corr;
   }
   static void *newArray_mom_corr(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::mom_corr[nElements] : new ::mom_corr[nElements];
   }
   // Wrapper around operator delete
   static void delete_mom_corr(void *p) {
      delete ((::mom_corr*)p);
   }
   static void deleteArray_mom_corr(void *p) {
      delete [] ((::mom_corr*)p);
   }
   static void destruct_mom_corr(void *p) {
      typedef ::mom_corr current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::mom_corr

/********************************************************
* mom_corrDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablemom_corrDict();

extern "C" void G__set_cpp_environmentmom_corrDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("mom_corr.h");
  G__cpp_reset_tagtablemom_corrDict();
}
#include <new>
extern "C" int G__cpp_dllrevmom_corrDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* mom_corr */
static int G__mom_corrDict_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((mom_corr*) G__getstructoffset())->correct_thel_e1_2039_2250_feb09((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mom_corrDict_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((mom_corr*) G__getstructoffset())->correct_pel_e1_2039_2250_feb09((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic default constructor
static int G__mom_corrDict_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   mom_corr *p;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new mom_corr[n];
     } else {
       p = new((void*) gvp) mom_corr[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new mom_corr;
     } else {
       p = new((void*) gvp) mom_corr;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mom_corrDictLN_mom_corr));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__mom_corrDict_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   mom_corr* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new mom_corr(*(mom_corr*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mom_corrDictLN_mom_corr));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef mom_corr G__Tmom_corr;
static int G__mom_corrDict_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (mom_corr*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((mom_corr*) (soff+(sizeof(mom_corr)*i)))->~G__Tmom_corr();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (mom_corr*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((mom_corr*) (soff))->~G__Tmom_corr();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__mom_corrDict_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   mom_corr* dest = (mom_corr*) G__getstructoffset();
   const mom_corr& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* mom_corr */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmom_corrDict {
 public:
  G__Sizep2memfuncmom_corrDict(): p(&G__Sizep2memfuncmom_corrDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmom_corrDict::*p)();
};

size_t G__get_sizep2memfuncmom_corrDict()
{
  G__Sizep2memfuncmom_corrDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemom_corrDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemom_corrDict() {

   /* Setting up typedef entry */
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__mom_corrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mom_corrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mom_corrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mom_corrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mom_corrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__mom_corrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mom_corrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mom_corrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mom_corrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mom_corrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* mom_corr */
static void G__setup_memvarmom_corr(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mom_corrDictLN_mom_corr));
   { mom_corr *p; p=(mom_corr*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmom_corrDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncmom_corr(void) {
   /* mom_corr */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mom_corrDictLN_mom_corr));
   G__memfunc_setup("correct_thel_e1_2039_2250_feb09",2621,G__mom_corrDict_168_0_1, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"d - - 0 - pe d - - 0 - theta "
"d - - 0 - phi", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("correct_pel_e1_2039_2250_feb09",2513,G__mom_corrDict_168_0_2, 100, -1, G__defined_typename("Double_t"), 0, 3, 1, 1, 0, 
"d - - 0 - pe d - - 0 - theta "
"d - - 0 - phi", (char*)NULL, (void*) NULL, 0);
   // automatic default constructor
   G__memfunc_setup("mom_corr", 862, G__mom_corrDict_168_0_3, (int) ('i'), G__get_linked_tagnum(&G__mom_corrDictLN_mom_corr), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("mom_corr", 862, G__mom_corrDict_168_0_4, (int) ('i'), G__get_linked_tagnum(&G__mom_corrDictLN_mom_corr), -1, 0, 1, 1, 1, 0, "u 'mom_corr' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~mom_corr", 988, G__mom_corrDict_168_0_5, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__mom_corrDict_168_0_6, (int) ('u'), G__get_linked_tagnum(&G__mom_corrDictLN_mom_corr), -1, 1, 1, 1, 1, 0, "u 'mom_corr' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmom_corrDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmom_corrDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmom_corrDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mom_corrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__mom_corrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mom_corrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__mom_corrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mom_corrDictLN_mom_corr = { "mom_corr" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemom_corrDict() {
  G__mom_corrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__mom_corrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mom_corrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__mom_corrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mom_corrDictLN_mom_corr.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemom_corrDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__mom_corrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__mom_corrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mom_corrDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__mom_corrDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mom_corrDictLN_mom_corr),sizeof(mom_corr),-1,0,(char*)NULL,G__setup_memvarmom_corr,G__setup_memfuncmom_corr);
}
extern "C" void G__cpp_setupmom_corrDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupmom_corrDict()");
  G__set_cpp_environmentmom_corrDict();
  G__cpp_setup_tagtablemom_corrDict();

  G__cpp_setup_inheritancemom_corrDict();

  G__cpp_setup_typetablemom_corrDict();

  G__cpp_setup_memvarmom_corrDict();

  G__cpp_setup_memfuncmom_corrDict();
  G__cpp_setup_globalmom_corrDict();
  G__cpp_setup_funcmom_corrDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmom_corrDict();
  return;
}
class G__cpp_setup_initmom_corrDict {
  public:
    G__cpp_setup_initmom_corrDict() { G__add_setup_func("mom_corrDict",(G__incsetup)(&G__cpp_setupmom_corrDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmom_corrDict() { G__remove_setup_func("mom_corrDict"); }
};
G__cpp_setup_initmom_corrDict G__cpp_setup_initializermom_corrDict;

